"""added roles

Revision ID: 88564143d689
Revises: e4356e74cf65
Create Date: 2025-09-05 21:09:17.487251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88564143d689'
down_revision = 'e4356e74cf65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
